name: Build and Deploy
on:
  push:
    branches:
      - master
  # pull_request:
  #   branches:
  #     - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}

    - name: Install dependencies
      run: npm install

    # - name: Run the tests
    #   run: npm test

    - name: Build
      run: npm run build --prod --base-href "https://botoom.github.io/${repository}/"
    - name: Deploy
      run: |
        git config --global user.name $user_name
        git config --global user.email $user_email
        git remote set-url origin https://${github_token}@github.com/${repository}
        npx angular-cli-ghpages --dir=dist/${repository}
      env:
        user_name: 'BOTOOM'
        user_email: 'eddiazr@correo.udistrital.edu.co'
        github_token: ${{ secrets.ACCESS_TOKEN }}
        repository: ${{ github.repository }}
